language: python
sudo: false
python:
  - '2.6'
  - '2.7'
script:
  - python ./setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 solvebio; fi
install:
  - pip install flake8
  # We use @skipIf so unittest2 is needed on Pyton 2.6
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
notifications:
  slack:
    secure: WvTImIlFKtCSTrcpk11RB467ybQBmZatk1k9CEEb5qkRRX0IUhmmNzV4xKIJR40Hf1u84uW6j5AeD/OChHycU+1C/OmMgyFAIYMAkE8db+dGtpdlQO5a5Jj9xzK8nfUKrw6Y3JzDTn+mQkeFyRP6D8fj3WPWOV5G9EOTY62sLiQ=
